# ---- build stage ----
FROM node:20-alpine AS build
WORKDIR /app

# Install deps first (better cache)
COPY package*.json ./
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build

# ---- run stage ----
FROM nginx:alpine
# Replace default nginx site config (optional, but nice)
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy built assets to nginx html folder
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
